#!/bin/bash
set -euo pipefail

# === Apply Egress Firewall Rules (macOS pf) ===
# Reads allowlist.conf, resolves hostnames to IPs, and applies pf anchor
# rules to the Docker bridge interface. Only allowlisted host:port pairs
# can receive outbound TCP connections from the egress network.
#
# Usage: sudo bash apply-rules.sh [allowlist-file] [network-name]
#
# Requires: sudo (pf needs root), Docker running, dig (for DNS resolution).
#
# IMPORTANT: pf rules do not survive reboot. Run this after every restart,
# or add to a LaunchDaemon that runs before the OpenClaw gateway starts.
#
# NOTE: Docker Desktop and OrbStack on macOS run containers inside a Linux VM.
# The bridge interface exists inside the VM, not on the macOS host, so pf rules
# targeting the bridge won't take effect. This script checks for the interface
# and exits with a clear error if it is not found on the host.

# Color output (disabled when not writing to a terminal)
if [ -t 1 ]; then
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    YELLOW='\033[1;33m'
    BOLD='\033[1m'
    NC='\033[0m'
else
    RED='' GREEN='' YELLOW='' BOLD='' NC=''
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ALLOWLIST="${1:-$SCRIPT_DIR/allowlist.conf}"
NETWORK_NAME="${2:-openclaw-egress}"
ANCHOR="openclaw-egress"

echo ""
echo -e "${BOLD}=== Apply Egress Rules (macOS pf) ===${NC}"
echo ""

# ── Preflight ──────────────────────────────────────────────────

if [[ "$(uname)" != "Darwin" ]]; then
    echo -e "${RED}This script is for macOS only${NC}"
    echo "Use apply-rules-linux.sh for Linux"
    exit 1
fi

if [[ $EUID -ne 0 ]]; then
    echo -e "${RED}Must run with sudo${NC}"
    echo "Usage: sudo bash $0 [allowlist] [network-name]"
    exit 1
fi

if [[ ! -f "$ALLOWLIST" ]]; then
    echo -e "${RED}Allowlist not found: $ALLOWLIST${NC}"
    exit 1
fi

if ! command -v docker &>/dev/null; then
    echo -e "${RED}Docker not found${NC}"
    exit 1
fi

if ! docker network inspect "$NETWORK_NAME" &>/dev/null; then
    echo -e "${RED}Network '$NETWORK_NAME' not found — run setup-network.sh first${NC}"
    exit 1
fi

if ! command -v dig &>/dev/null; then
    echo -e "${RED}dig not found — install with: brew install bind${NC}"
    exit 1
fi

# ── Resolve bridge interface ───────────────────────────────────

IFACE=$(docker network inspect "$NETWORK_NAME" --format '{{index .Options "com.docker.network.bridge.name"}}' 2>/dev/null || echo "")
if [[ -z "$IFACE" ]]; then
    NETWORK_ID=$(docker network inspect "$NETWORK_NAME" --format '{{.Id}}' 2>/dev/null || echo "")
    if [[ -n "$NETWORK_ID" ]]; then
        IFACE="br-${NETWORK_ID:0:12}"
    fi
fi

if [[ -z "$IFACE" ]]; then
    echo -e "${RED}Cannot determine bridge interface for network '$NETWORK_NAME'${NC}"
    echo "Start a container on the network first, then re-run"
    exit 1
fi

# Verify the bridge interface actually exists on the host. Docker Desktop and
# OrbStack run containers inside a Linux VM — the bridge is inside that VM,
# so host-level pf rules won't work.
if ! ifconfig "$IFACE" &>/dev/null; then
    echo -e "${RED}Bridge interface '$IFACE' not found on host${NC}"
    echo ""
    echo "Docker Desktop and OrbStack run containers inside a Linux VM."
    echo "The bridge interface exists inside the VM, not on macOS, so"
    echo "host-level pf rules cannot filter container egress traffic."
    echo ""
    echo "Options:"
    echo "  - Use a Linux VM with apply-rules-linux.sh (nftables inside VM)"
    echo "  - Use colima with bridged networking"
    exit 1
fi

echo "Network:   $NETWORK_NAME"
echo "Interface: $IFACE"
echo "Allowlist: $ALLOWLIST"
echo ""

# ── Ensure pf anchor exists in main ruleset ────────────────────

PF_CONF="/etc/pf.conf"
ANCHOR_LINE="anchor \"$ANCHOR\""
if ! grep -qF "$ANCHOR_LINE" "$PF_CONF" 2>/dev/null; then
    echo -e "${YELLOW}Adding anchor to $PF_CONF...${NC}"
    # Backup before modifying
    cp "$PF_CONF" "${PF_CONF}.bak.$(date +%Y%m%d%H%M%S)"
    echo "$ANCHOR_LINE" >> "$PF_CONF"
    echo -e "${GREEN}Anchor added${NC}"
fi

# ── Build rules from allowlist ─────────────────────────────────

echo -e "${BOLD}Resolving allowlist entries...${NC}"

RULES="# Auto-generated by apply-rules.sh — do not edit manually\n"
RULES+="# Regenerate with: sudo bash apply-rules.sh\n\n"

# Default deny all outbound on the bridge interface
RULES+="block out log on $IFACE all\n\n"

# Allow DNS (containers need to resolve hostnames)
RULES+="pass out quick on $IFACE proto udp to any port 53\n"
RULES+="pass out quick on $IFACE proto tcp to any port 53\n\n"

ENTRY_COUNT=0
RESOLVE_FAILURES=0

while IFS= read -r line; do
    # Strip comments and whitespace
    line="${line%%#*}"
    line="${line// /}"
    [[ -z "$line" ]] && continue

    host="${line%%:*}"
    port="${line#*:}"

    # Resolve hostname to IPs
    IPS=$(dig +short "$host" A 2>/dev/null | grep -E '^[0-9]+\.' || true)

    if [[ -z "$IPS" ]]; then
        echo -e "  ${YELLOW}WARN: $host — no A records, skipping${NC}"
        RESOLVE_FAILURES=$((RESOLVE_FAILURES + 1))
        continue
    fi

    for ip in $IPS; do
        if [[ "$port" != "$host" ]]; then
            RULES+="pass out quick on $IFACE proto tcp to $ip port $port  # $host\n"
        else
            RULES+="pass out quick on $IFACE proto tcp to $ip  # $host (all ports)\n"
        fi
    done
    ENTRY_COUNT=$((ENTRY_COUNT + 1))
    echo "  $host:${port:-*} -> $(echo "$IPS" | tr '\n' ' ')"
done < "$ALLOWLIST"

echo ""

if [[ "$ENTRY_COUNT" -eq 0 ]]; then
    echo -e "${RED}No valid allowlist entries — refusing to apply (would block all traffic)${NC}"
    exit 1
fi

# ── Apply rules ────────────────────────────────────────────────

echo -e "$RULES" | pfctl -a "$ANCHOR" -f - 2>/dev/null
pfctl -e 2>/dev/null || true

echo -e "${GREEN}pf rules applied to anchor: $ANCHOR${NC}"
echo "  Entries: $ENTRY_COUNT"
if [[ "$RESOLVE_FAILURES" -gt 0 ]]; then
    echo -e "  ${YELLOW}DNS failures: $RESOLVE_FAILURES (review warnings above)${NC}"
fi
echo ""

# ── Show active rules ──────────────────────────────────────────

echo -e "${BOLD}Active rules in anchor '$ANCHOR':${NC}"
pfctl -a "$ANCHOR" -sr 2>/dev/null || echo "  (no rules — pfctl error)"
echo ""

echo -e "${BOLD}Verify with:${NC}"
echo "  bash $(dirname "$0")/verify-egress.sh"
echo ""
echo -e "${YELLOW}NOTE: pf rules do not survive reboot.${NC}"
echo "Add this script to a LaunchDaemon or run after every restart."
echo ""
